# docker file for restaurant management django backend
FROM python:3.11-slim
WORKDIR /app
COPY . /app
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 8000
CMD python manage.py migrate --noinput && \
    python manage.py runserver 0.0.0.0:8000
